
##########################################
#     Change these variables !important
##########################################
# Set this to your main site title. If page doesn't have its own title,# then this title will be used.
title: Guru's Dummy Blog
# Set your host if deployed not locally # For example "https://yourGitHub.github.io"
url: http://www.gurucharan.in
logo: /resources/images/logo.png

# Default Image For Social Share if no image is specified in the page YAML Front Matter
defaults:
  - scope:
      path: ""
    values:
      image: 
        twitter: /resources/images/logo.png
        facebook: /resources/images/logo.png

twitter:
  username: Gurucharan94

facebook:
  publisher: https://www.facebook.com/gurucharan1994

author:
  twitter: Gurucharan94

social:
  name: Gurucharan
  links:
    - https://www.facebook.com/gurucharan1994
    - https://www.linkedin.com/in/gurucharan94
    - https://github.com/gurucharan94
    - https://twitter.com/GuruCharan94

quote:
  enable: false
  quote: Some fancy quote
  author: John Doe

# Following needed for disqus integration # Set your 'disqus' account name
disqus: gurucharan
#Footer
footer-links:
  facebook: gurucharan1994
  github: GuruCharan94
  linkedin: gurucharan94
  twitter: Gurucharan94


# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
# NOTE! only change if site is NOT in master's branch
baseurl:

# Change this to your google analytics ID
google_analytics: UA-89662853-1
google_site_verification: k_yVXly_gCfHfxCfirzHqNFWnt6ZU5f0L88m351p3fk
# Add this ID  www.addthis.com
addthis: ra-5879f7fffac9b3c6

# Contact form pupublic key
contact_PK: 6b74036d69c0b885256365847afd94d2

##########################################
#          Optional variables
##########################################

# Set maximum posts per page
paginate: 10

# Set permalink
permalink: pretty

##########################################
#          Do not change these variables
##########################################

include:
  - _pages

sass:
  sass_dir: _sass
sass:
    style: compressed

gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file
  - jekyll-seo-tag

paginate_path: /_pages/page:num

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
